apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: edzac010e-go 
  janus-idp.io/tekton: edzac010e-go
  backstage.io/kubernetes-id: edzac010e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: edzac010e-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  